whenever sqlerror continue

drop table FEESTRANSACTION;

whenever sqlerror exit failure;

CREATE TABLE  FEESTRANSACTION(
STUDENT_ID                VARCHAR2(200),    
STUDENT_COURSE_NAME        VARCHAR2(200),  
STUDENT_SEM_NAME           VARCHAR2(200),  
STUDENT_TFEE               VARCHAR2(200),
STUDENT_FINE               VARCHAR2(200),
STUDENT_SFEE               VARCHAR2(200),
STUDENT_FEE_SUBMISION_DATE  VARCHAR2(200),
STUDENT_FEESTATUS          VARCHAR2(200),  

CONSTRAINT PK_FEESTRANSACTION_ID PRIMARY KEY (STUDENT_ID , STUDENT_COURSE_NAME, STUDENT_SEM_NAME)
);
